@startuml
left to right direction
actor "Пользователь" as user
rectangle AIMuseStudio {
  usecase "Текст" as UC1
  usecase "Изображение" as UC2
  usecase "Аудио" as UC3
  usecase "Видео" as UC4
}
rectangle Текст {
  usecase "Сгенерировать текст" as TUC1
  usecase "Рерайт текста" as TUC2
}
rectangle Изображение {
  usecase "Убрать фон" as IUC1
  usecase "..." as IUC2
}
rectangle Аудио {
  usecase "Убрать шум" as AUC1
  usecase "..." as AUC2
}
rectangle Видео {
  usecase "Убрать фон" as VUC1
  usecase "..." as VUC2
}
user --> UC1
UC1 --> TUC1
UC1 --> TUC2
user --> UC2
UC2 --> IUC1
UC2 --> IUC2
user --> UC3
UC3 --> AUC1
UC3 --> AUC2
user --> UC4
UC4 --> VUC1
UC4 --> VUC2
@enduml


